# Generated by Django 5.0 on 2023-12-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='callAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tts', models.TextField()),
                ('negative_score', models.DecimalField(decimal_places=5, max_digits=12)),
                ('positive_score', models.DecimalField(decimal_places=5, max_digits=12)),
                ('neutral_score', models.DecimalField(decimal_places=5, max_digits=12)),
                ('compound_score', models.DecimalField(decimal_places=5, max_digits=12)),
                ('Emotion', models.CharField(max_length=30)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.callhistory')),
            ],
        ),
    ]
