# Generated by Django 5.0 on 2023-12-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.CharField(choices=[('M', 'Manager'), ('E', 'Employee')], default='E', max_length=1),
        ),
    ]
