# Generated by Django 5.0 on 2023-12-20 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_callhistory_duration_callanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('feedbackFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_from', to=settings.AUTH_USER_MODEL)),
                ('feedbackTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
